# recipes/recipe.yml
name: FoamyOS
description: one heap of a cool OS

base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest

config:
  - type: rpm-ostree
    install:
      - firefox       
      - neovim        
      - git           
      - curl
      - loupe                 
      - nautilus              
      - gnome-control-center  
      - gnome-tweaks          
      - extension-manager     
      - gnome-calculator      
      - gnome-clocks          
      - gnome-console         
      - baobab                
      - gnome-disk-utility    
      - gnome-font-viewer     
      - gnome-logs            
      - gnome-software        
    remove:
      - gnome-tour    
      - yelp                  
